### ISSUE TITLE
BrowserSync watch on wrong folder path

### ISSUE THREAD

**Issue by abusedmedia** [todotoit/octo-happiness#13]
BrowserSync with `grunt dev` will look at `.grunt/app` instead `app` folder because `__dirname` is `.grunt/config` 

It can be fixed easily by changing in this line:
https://github.com/todotoit/octo-happiness/blob/master/.grunt/config/browserSync.js#L18

`..` with `../..`

Or maybe there are other ways...

**Comment by endorama** [comment]
there is a `rootPath` option available, the `__dirname` use here is incorrect

**Comment by abusedmedia** [comment]
Fixed on master
